# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnSplash_Rodrigo_Elo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnSplash_Rodrigo_Elo

	pod 'Alamofire', '~> 4.7'
    pod 'Kingfisher', '~> 4.0'
    pod 'UIColor_Hex_Swift', '~> 4.0.1'
end
